name: Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - run: mvn -B -pl cli -am clean package verify -P mac
      - uses: actions/upload-artifact@v3
        with:
          name: pfm-mac
          path: cli/target/dist/*.dmg

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - run: mvn -B -pl cli -am clean package verify -P windows
      - uses: actions/upload-artifact@v3
        with:
          name: pfm-win
          path: cli/target/dist/*.msi, cli/target/dist/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - run: mvn -B -pl cli -am clean package verify -P linux
      - uses: actions/upload-artifact@v3
        with:
          name: pfm-linux
          path: cli/target/dist/*.deb
