name: Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build DMG Installer
        run: mvn -B -pl cli -am clean package verify -P mac
      - name: Upload Mac Installer
        uses: actions/upload-artifact@v4
        with:
          name: pfm-mac
          path: cli/target/dist/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build Windows Installer
        run: mvn -B -pl cli -am clean package verify -P windows
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: pfm-win
          path: cli/target/dist/*.{msi,exe}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build Linux DEB
        run: mvn -B -pl cli -am clean package verify -P linux
      - name: Upload Linux Installer
        uses: actions/upload-artifact@v4
        with:
          name: pfm-linux
          path: cli/target/dist/*.deb
