name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  collect-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download packaged artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-collect

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-collect/**/**/*.dmg
            dist-collect/**/**/*.msi
            dist-collect/**/**/*.exe
            dist-collect/**/**/*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
