name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Download macOS artifacts
      - name: Download macOS artifacts
        uses: actions/download-artifact@v3
        with:
          name: pfm-mac
          path: dist/mac

      # Download Windows artifacts
      - name: Download Windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: pfm-win
          path: dist/windows

      # Download Linux artifacts
      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: pfm-linux
          path: dist/linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/mac/*.dmg
            dist/windows/**/*.{exe,msi}
            dist/linux/*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
