name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Mac Installer
        uses: actions/download-artifact@v4
        with:
          name: pfm-mac
          path: dist/mac

      - name: Download Windows Installer
        uses: actions/download-artifact@v4
        with:
          name: pfm-win
          path: dist/windows

      - name: Download Linux Installer
        uses: actions/download-artifact@v4
        with:
          name: pfm-linux
          path: dist/linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/mac/*.dmg
            dist/windows/*.{exe,msi}
            dist/linux/*.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
